### ISSUE TITLE
Different permission for different folder?

### ISSUE THREAD

**Issue by MagePsycho** [capistrano/file-permissions#21]
How to set different permission/ownership to a different folder?
I think the approach is not flexible.

**Comment by will-in-wi** [comment]
I don't personally use this gem, but I agree that it isn't flexible. I think that it is supposed to solve a very specific problem around deployment as one user and running the app as a different one.

If you want a different behavior, I'd direct you to https://github.com/capistrano/file-permissions/blob/master/lib/capistrano/tasks/file-permissions.rake, which you can copy into your project and modify however you want.

If you have a specific feature request or such, feel free to post that. This issue as written is hard to translate into an actionable change or improvement.
